version: 2.1

jobs:
  test:
    docker:
      - image: node:8.12.0
    steps:
      - checkout
      - run:
          name: Install package.json
          command: npm install
      - run:
          name: Run All
          command: ./node_modules/.bin/nyc -e .jsx npm test
      - run:
          name: Cover
          command: ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov
      - run:
          when: on_success
          command: ./node_modules/.bin/codecov


workflows:
  version: 2
  test:
    jobs:
      - test
